// <auto-generated />
using System;
using BiliMusic.SqliteModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BiliMusic.SqliteModel.Migrations
{
    [DbContext(typeof(BiliMusicContext))]
    [Migration("20190315063840_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("BiliMusic.SqliteModel.SearchHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("content");

                    b.Property<DateTime>("datetime");

                    b.HasKey("id");

                    b.ToTable("SearchHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
